### PR TITLE
Make Meeting Date Dynamic

### LINKED ISSUE #44: Dynamic date for next TL Meetup
Make the date for the next TechLancaster dynamic instead of being hard-coded HTML which needs to be changed every month.

### PR DESCRIPTION
**Pull request by amayer5125**
I didnt test this code. If someone could review it and test it that would be awesome!

Closes #44

### CODE REVIEW

**Comment by brewcore** [comment]
Going to test it live and see what happens.

**Comment by brewcore** [comment]
Looks like it's printing 3 Tuesdays from today, rather than the third Tuesday.  I'll figure it out.

**Comment by amayer5125** [comment]
Maybe it needs to be `third tuesday this month`

**Comment by brewcore** [comment]
`this month` had no effect.  `third tuesday november 2016` printed the 22nd. Closer, but still wrong.

**Pull request merged**
